### ISSUE TITLE
The option to have two joysticks

### ISSUE THREAD

**Issue by harrycollin** [Fried-Chicken/three-joystick#1]
It would be great to have the option to have multiple joysticks. Maybe one on each half of the screen? This would make it easier to develop experiences where the user needs to look and move simultaneously. 

Something like this 
![image](https://user-images.githubusercontent.com/10602138/144418702-ed4d50c9-9dc1-41c4-bbca-ac9df2fe9faf.png)

**Comment by SimonMo88** [comment]
That should be possible. Maybe I can create a demo to show this.

**Comment by crunchwrap89** [comment]
Hi, it would be great to see a demo of this if possible?
